# Generated by Django 4.0.1 on 2024-03-22 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='claim',
            old_name='claimer',
            new_name='user',
        ),
    ]
